dist: xenial
language: cpp
compiler: gcc
required: sudo
env:
  global:
    - TRAVIS=true
    - DEPENDENCY_URL=https://github.com/hexoxide/raspberry-dependency.git
addons:
  apt:
    packages:
      - git
      - ant
      - lcov
      - wget
      - htop
      - make
      - libtool
      - clang
      - clang-tidy
      - doxygen
      - automake
      - autoconf
      - zookeeper
      - python-dev
      - icu-devtools
      - libcppunit-dev
      - libzookeeper-mt-dev
before_install:
  - git clone $DEPENDENCY_URL depdendency
  - cd depdendency
  - git checkout O2v2
  - git submodule update --init --recursive
  - ./install-dependencies.sh > dependencies-report.txt
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - if [ ! -d "build" ]; then mkdir build; fi
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODECOV=true -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - make -j 2
  - cd ${TRAVIS_BUILD_DIR}/build
  - sudo python ../tests/run-clang-tidy.py -header-filter='.*' -checks='modernize*'
  - make coverage
after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
